language: ruby
rvm:
- 2.1.0
before_install:
  - gem install bundler
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake cucumber
  - bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: "ShC0LWFz8V/8xqv9X+/tegggaD7I2w9KJxRpxFEspon494TZyJTBhJD33SRl7V1Ewh3GpvHjwPDqJXpU0K8SpBwdVA0IjtaRpmWcZQdqB+qrQR5XJBAh6HtB6czlanU7WPJQCvo+SQdhTlO4WERlR0+tfz0XCiqHfWgT3i4HOqM="
  app:
    develop: codealia-sampriti
notifications:
  email:
    - info@agileventures.org
